refactor updates
rejuve-bio/AI-Assistant pull request #13
Opened 2024-11-13 15:33 UTC by kewserseid

2024-11-14 09:36 UTC, dawit-melka commented on app/prompts/summarizer_prompts.py
> +- Explain any notable gene-transcript relationships, including any genes that have a higher number of associated transcripts or complex transcriptional processes.
Do we really need to specify `gene-transcript`. It might affect the response to focus on those entities

2024-11-14 09:36 UTC, dawit-melka commented on app/prompts/summarizer_prompts.py
> +                  - Explain any notable gene-transcript relationships, including any genes that have a higher number of associated transcripts or complex transcriptional
same here.

2024-11-14 09:36 UTC, dawit-melka commented on app/main.py
> +            "such as identifying genes, proteins, terms, SNPs, transcripts, or interactions. "
I think it is also worth to notify the agent that it has access to bio knowledge graph

2024-11-14 09:40 UTC, kewserseid commented on app/prompts/summarizer_prompts.py
> +- Explain any notable gene-transcript relationships, including any genes that have a higher number of associated transcripts or complex transcriptional processes.
sure. i am working on updatingthe graph summarizer prompt in general

2024-11-14 09:41 UTC, kewserseid commented on app/prompts/summarizer_prompts.py
> +                  - Explain any notable gene-transcript relationships, including any genes that have a higher number of associated transcripts or complex transcriptional
sure.

2024-11-21 11:04 UTC, dawit-melka requested changes

2024-11-21 11:04 UTC, dawit-melka commented on app/routes.py
> +        response = AiAssistance(llm,schema_text).assistant_response(query,graph,user,graph_id)
Isn't it better to use the already defined `AiAssistance` object in the `__init__` constructor? Initializing the class for every request might not be efficient. and I think now the class accepts SchemaHandler instead of schema text.

2024-11-21 11:52 UTC, dawit-melka commented on app/routes.py
> +        response = AiAssistance(llm,schema_text).assistant_response(query,graph,user,graph_id)
Other that that all looks good to me!

2024-11-22 09:23 UTC, dawit-melka approved these changes

2024-11-22 09:23 UTC, merged